### ISSUE TITLE
[DOS] nothing is working to compile

### ISSUE THREAD

**Issue by gityman** [fgsfdsfgs/sm64-port#101]
I tried the docker method, I tried the makefile method, but nothing, NOTHING was working at all. so please help me, dear god.

**Comment by fgsfdsfgs** [comment]
Elaborate? What errors are you getting?

**Comment by gityman** [comment]
something that said, docker: error during connect: Head "http://%2F%2F.%2Fpipe%2FdockerDesktopLinuxEngine/_ping": open //./pipe/dockerDesktopLinuxEngine: The system cannot find the file specified.
and the same with running except with:
See 'docker run --help'. added

**Comment by fgsfdsfgs** [comment]
How are you running Docker? Are you on Linux or Windows or OSX? What errors do you get when trying to compile by hand?

**Comment by MasterNama17083** [comment]
![image](https://github.com/user-attachments/assets/4fa237c1-80a4-4780-9b8a-76cc4e459702)
I was compiling on this DOS version but didn't work at all. I've used on my laptop with windows 10.
(btw, I'm on ubuntu WSL).

Is there any ways to fix this?

**Comment by MasterNama17083** [comment]
nvm, yesterday I've compiled without docker result in fail. I've been installed docker on ubuntu wsl and re-cloning source code it worked.

**Comment by gityman** [comment]
on windows, I tried followed the guide but it was just refusing to run at all. then it stopped building the image properly

**Comment by gityman** [comment]
hell, I even used the %cd% method but it stopped in the middle of compiling!

**Comment by gityman** [comment]
closing this because you actually need to have cmd opened with administrator privileges in order for it to work
