### ISSUE TITLE
[DOS] Where's the graphics configuration?

### ISSUE THREAD

**Issue by MasterNama17083** [fgsfdsfgs/sm64-port#103]
![image](https://github.com/user-attachments/assets/8fd97f9b-c4a2-4fb9-b922-710a56f48d94)
I can't find on the source code, where's there way to toggle with on like config file?

**Comment by fgsfdsfgs** [comment]
These are appended to the `make` command when you build the game. Make sure to run `make clean` before rebuilding with new settings.

**Comment by MasterNama17083** [comment]
> These are appended to the `make` command when you build the game. Make sure to run `make clean` before rebuilding with new settings.

![image](https://github.com/user-attachments/assets/eb3e9c64-506a-4c33-96c9-1f3bf945f782)
Oh, thanks! I figured out to build using 3Dfx option with this command.
`docker run --rm --mount type=bind,source="$(pwd)",destination=/sm64 -ti sm64_dos make -j4 ENABLE_OPENGL_LEGACY=1 DOS_GL=dmesa` then put a `glide3x.dxe` in the build folder.
