### ISSUE TITLE
can't compile when enabling

### ISSUE THREAD

**Issue by soviet9922** [fgsfdsfgs/sm64-port#18]
Hi following the docker example on how to compile i can do it ok for the dos version.
But if try to enable DOS_GL=dmesa to run it on my 3dfx card got this error:

docker run --rm --mount type=bind,source="$(pwd)",destination=/sm64 -ti sm64_dos make -j4 ENABLE_OPENGL_LEGACY=1 DOS_GL=dmesa

ows_mustache.o build/us_dos/src/goddard/dynlists/anim_group_1.o -lm -no-pie -Llib/allegro -lalleg  -Llib/dmesa -lgl -Llib/glide3 -lglide3i
build/us_dos/src/pc/gfx/gfx_dos_api.o:gfx_dos_api.c:(.text+0x2da): undefined reference to `OSMesaDestroyContext'
build/us_dos/src/pc/gfx/gfx_dos_api.o:gfx_dos_api.c:(.text+0x7d2): undefined reference to `OSMesaCreateContextExt'
build/us_dos/src/pc/gfx/gfx_dos_api.o:gfx_dos_api.c:(.text+0x7fa): undefined reference to `OSMesaMakeCurrent'
build/us_dos/src/pc/gfx/gfx_dos_api.o:gfx_dos_api.c:(.text+0x80c): undefined reference to `OSMesaPixelStore'
collect2: error: ld returned 1 exit status
Makefile:921: recipe for target 'build/us_dos/sm64.us.f3dex2e.exe' failed
make: *** [build/us_dos/sm64.us.f3dex2e.exe] Error 1

**Comment by fgsfdsfgs** [comment]
You have to either do `make clean` or delete the `build` folder before recompiling with different settings.
