### ISSUE TITLE
Graphics corruption at Cool, Cool Mountain (PS2)

### ISSUE THREAD

**Issue by stranno** [fgsfdsfgs/sm64-port#2]
![file](https://user-images.githubusercontent.com/6293197/92999772-e43bb480-f523-11ea-94ba-f7371bb05025.gif)

Party time at Mushroom Kingdom it seems 😄

It happened in that point at Cool, Cool Mountain, transporting the little penguin. Once you complete the level the game keeps corrupted.

**Comment by fgsfdsfgs** [comment]
That is much more likely a more general issue of "the game runs out of VRAM and doesn't do anything about it". I haven't gotten around to properly handling that yet. But thank you for testing.

**Comment by mkst** [comment]
I have to say. That looks awesome.

**Comment by fgsfdsfgs** [comment]
This *might* be fixed in the latest commit. Haven't played long enough to check.

**Comment by fgsfdsfgs** [comment]
This *might* be fixed *for real* in the latest commit. Played through a few texture cache flushes and it seems to be fine.

**Comment by MattE32** [comment]
After some time playing, after the bowser boat the game just looks like this:

![20200916_165040](https://user-images.githubusercontent.com/71407511/93386586-4bb47580-f83e-11ea-915b-d4b6db51da32.jpg)

And thanks for making the port, I haven't had fun with something in a while

**Comment by fgsfdsfgs** [comment]
Is this the latest commit?

**Comment by stranno** [comment]
I guess this could be closed since someone already speedrun through it. I will test and close it if everythings alright.

**Comment by maxjf1** [comment]
is there any learning material you could provide, so we can help with the port. I would love to help, but i know only basics of C and assembly

**Comment by fgsfdsfgs** [comment]
I learned mostly by looking at [ps2sdk](https://github.com/ps2dev/ps2sdk) samples and [gsKit](https://github.com/ps2dev/gsKit) examples and source code. The only thing that runs on the IOP in this port is the audio server, so for ps2sdk you only really need the samples from the `ee` directory.

**Comment by stranno** [comment]
I have played one more hour and no graphics break so far. Issue closed.

**Comment by fgsfdsfgs** [comment]
Reopening this since a different kind of corruption now apparently happens if enough texture cache flushes happen.

**Comment by fgsfdsfgs** [comment]
The "new" corruption was not related to VRAM at all, but to RAM.
The game used to allocate a 128-aligned buffer in RAM for every texture for DMA transfer purposes (because the textures can be loaded and unloaded at any time), but even though those buffers were eventually freed it would result in memory fragmentation and eventual untimely death from OOM.
This is fixed in d700400: transferable texture data are now stored in a single RAM buffer that is allocated once on startup.
