### ISSUE TITLE
Xbox version causes "System Halted" on real Xbox hardware

### ISSUE THREAD

**Issue by chunkyjackson** [fgsfdsfgs/sm64-port#23]
Built with docker, copied the "default.xbe" to my Xbox HDD ran it from both XBMC & UnleashX both times got this: 
![IMG_20201005_124054](https://user-images.githubusercontent.com/72405993/95108758-b0f6da80-0709-11eb-89ac-e7b9e24ef097.jpg)

**Comment by fgsfdsfgs** [comment]
I know. I should have put it into the README.

**Comment by chunkyjackson** [comment]
I managed to build a Xbox executable that works on the real hardware using the patch and instructions from here https://github.com/mborgerson/xsm64/ it runs at 480p and has sound with a little slowdown. Maybe take a look at it see if you could get it running at 720p or 1080i (might be too much) or at least get the 60fps patch working (it's slow on the real hardware)

**Comment by fgsfdsfgs** [comment]
Yeah, that version uses a slightly different approach to graphics. I must have some bug in my code that causes garbage to be inserted into the graphics command buffer, causing the graphics glitches and the crash or something.

**Comment by fgsfdsfgs** [comment]
I have obtained an Xbox, so maybe now I can figure this shit out.

**Comment by fgsfdsfgs** [comment]
It should now be fixed. Can you try it again?

**Comment by chunkyjackson** [comment]
Ok built it, it starts! I know it doesn't have sound right now, runs in constant turbo mode. Mario head title screen has a white background. But other textures like the shadow under Mario are correct with no lines or doubling of one part of the texture.

**Comment by fgsfdsfgs** [comment]
Yeah, that's all gonna be fixed soon. Thanks for testing.

**Comment by chunkyjackson** [comment]
You're welcome, thank you for all your work!
