### ISSUE TITLE
PS3 - pkg doesn't work

### ISSUE THREAD

**Issue by crystalct** [fgsfdsfgs/sm64-port#27]
Inside Makefile change :
```
$(PKG) --contentid $(CONTENTID) $(BUILD_DIR)/pkg/ $@ >> /dev/null
cp $@ $(basename $@).gnpdrm.pkg
$(PACKAGE_FINALIZE) $(basename $@).gnpdrm.pkg

```
in
`
$(PKG) --contentid $(CONTENTID) $(BUILD_DIR)/pkg/ $@.pkg
`

**Comment by fgsfdsfgs** [comment]
You mean remove `>> /dev/null`? That isn't really going to do anything, but okay.
I added an easier to use `pkg` target in the latest commit, you can now just do `make pkg -j4` and it'll build one in `build/us_pc/`.

**Comment by crystalct** [comment]
No, i mean `$(PACKAGE_FINALIZE) $(basename $@).gnpdrm.pkg` produces a pkg that my real PS3 refuses....
`$(PKG) --contentid $(CONTENTID) $(BUILD_DIR)/pkg/ $@ >> /dev/null` produces a working pkg.
Of course, `>> /dev/null` is irrilevant.

**Comment by crystalct** [comment]
OK.... now make pkg produces sm64.us.f3dex2e.gnpdrm.pkg (not working for me) and sm64.us.f3dex2e.pkg (working for me).

Good.

**Comment by fgsfdsfgs** [comment]
I'm pretty sure it was doing that before.

**Comment by crystalct** [comment]
You are right... it's and it was `cp $@ $(basename $@).gnpdrm.pkg` and not `mv $@ $(basename $@).gnpdrm.pkg`.
Anyway, now there is `make pkg` ... it's better.
