### ISSUE TITLE
Xbox version crashes when both caps are collected in Dire Dire Docks

### ISSUE THREAD

**Issue by mememuseum** [fgsfdsfgs/sm64-port#29]
I've discovered this during the 120 star run I'm doing. Collecting both of the caps in Dire Dire Docks causes the game to crash.

Here is a picture of the error code:

![20201018_101056](https://user-images.githubusercontent.com/73069762/96372015-80139e00-112a-11eb-8be8-eaf8537787a7.jpg)

**Comment by fgsfdsfgs** [comment]
Didn't know that shader id was even used in the base game. You're not using any mods, right?
Guess maybe it happens when both those caps are active at the same time.

**Comment by mememuseum** [comment]
Nope, no mods. I used the same baserom that I used to compile all the other ports. Built it using the docker instructions.

**Comment by fgsfdsfgs** [comment]
Should be fixed in 24f9f2a. Please test if possible.
Unless that doesn't actually say `09200a00`.

**Comment by mememuseum** [comment]
I'll give it a go later and let you know if it works. I believe it says 09200a00. I should have written it down instead of taking a mediocre picture of it.

**Comment by mememuseum** [comment]
> Please test if possible.

It works fine now, and translucent Mario doesn't look funky anymore. I've also collected all 120 stars now so that makes the Xbox port completable with no game breaking issues.

**Comment by fgsfdsfgs** [comment]
Thanks.
