### ISSUE TITLE
ps2-audsrv does not clone or build (PS2)

### ISSUE THREAD

**Issue by stranno** [fgsfdsfgs/sm64-port#3]
Hey fgfdsfgs, there's something wrong in the Makefile with the audsrv module. I had to clone and build it in the ps2 subfolder in order to compile the new version.

Greetings.

**Comment by fgsfdsfgs** [comment]
Did you forget to clone with `--recursive` or do `git submodule update --init` after cloning? This is normal Git procedure for repos with submodules.

**Comment by stranno** [comment]
My apologies, you are right. I forget that.
