### ISSUE TITLE
Shader crash with Luigi (Xbox)

### ISSUE THREAD

**Issue by PootisDaMan** [fgsfdsfgs/sm64-port#32]
So I wanted to try and use Luigi on the Xbox port because of the recent release of the "L is Singleplayer 2401" mod and the memes but, a shader error occurred when using a wing cap.

![2020-11-12 11-37-24_Moment](https://user-images.githubusercontent.com/71825559/99137522-6c474480-25cf-11eb-9129-822c0a501cd6.jpg)

This happens with this mod as well as the Low Poly Promo96 Mario and Luigi. Oddly enough, Metal Cap and Vanish Cap still work fine.

**Comment by fgsfdsfgs** [comment]
That's cause shaders for this ID are not  in the `xbox/shaders` folder. This does not generate shaders at runtime, so it can only use the ones that it knows. I'll add the shaders for that ID I guess.

**Comment by fgsfdsfgs** [comment]
Try now, I've added them in 0caac79.

**Comment by PootisDaMan** [comment]
Just tested it and it works perfectly now. Can now get the wing cap as well as beat the game as Luigi.
