### ISSUE TITLE
Cannot apply 60FPS patch to Xbox source.

### ISSUE THREAD

**Issue by chunkyjackson** [fgsfdsfgs/sm64-port#34]
When trying to apply it with "git apply" I get the following errors:

error: patch failed: include/types.h:117
error: include/types.h: patch does not apply
error: patch failed: src/engine/graph_node.h:109
error: src/engine/graph_node.h: patch does not apply
error: patch failed: src/engine/surface_collision.c:7
error: src/engine/surface_collision.c: patch does not apply
error: patch failed: src/engine/surface_load.c:14
error: src/engine/surface_load.c: patch does not apply
error: patch failed: src/game/camera.c:483
error: src/game/camera.c: patch does not apply
error: patch failed: src/game/camera.h:654
error: src/game/camera.h: patch does not apply
error: patch failed: src/game/envfx_bubbles.c:35
error: src/game/envfx_bubbles.c: patch does not apply
error: patch failed: src/game/envfx_snow.c:54
error: src/game/envfx_snow.c: patch does not apply
error: patch failed: src/game/envfx_snow.h:25
error: src/game/envfx_snow.h: patch does not apply
error: patch failed: src/game/game_init.h:12
error: src/game/game_init.h: patch does not apply
error: patch failed: src/game/hud.c:57
error: src/game/hud.c: patch does not apply
error: patch failed: src/game/ingame_menu.c:111
error: src/game/ingame_menu.c: patch does not apply
error: patch failed: src/game/level_geo.c:34
error: src/game/level_geo.c: patch does not apply
error: patch failed: src/game/object_helpers.c:1549
error: src/game/object_helpers.c: patch does not apply
error: patch failed: src/game/paintings.c:189
error: src/game/paintings.c: patch does not apply
error: patch failed: src/game/rendering_graph_node.c:39
error: src/game/rendering_graph_node.c: patch does not apply
error: patch failed: src/game/screen_transition.c:16
error: src/game/screen_transition.c: patch does not apply
error: patch failed: src/menu/intro_geo.c:1
error: src/menu/intro_geo.c: patch does not apply
error: patch failed: src/pc/gfx/gfx_dxgi.cpp:34
error: src/pc/gfx/gfx_dxgi.cpp: patch does not apply
error: patch failed: src/pc/gfx/gfx_glx.c:21
error: src/pc/gfx/gfx_glx.c: patch does not apply
error: patch failed: src/pc/gfx/gfx_sdl2.c:139
error: src/pc/gfx/gfx_sdl2.c: patch does not apply
error: patch failed: src/pc/gfx/gfx_xbox_wapi.c:65
error: src/pc/gfx/gfx_xbox_wapi.c: patch does not apply
error: patch failed: src/pc/pc_main.c:82
error: src/pc/pc_main.c: patch does not apply

This started happening after updating to latest commit.

**Comment by fgsfdsfgs** [comment]
You sure you're not applying it to the wrong branch or something? Or the wrong patch to the `xbox` branch.

**Comment by chunkyjackson** [comment]
It must have not pulled correctly. Just re-downloaded and applied the patch normally.
