### ISSUE TITLE
Pre-built release?

### ISSUE THREAD

**Issue by ghost** [fgsfdsfgs/sm64-port#36]
Hi, I was wondering if there is a pre-built release of this, or if there ever will be?

**Comment by fgsfdsfgs** [comment]
Not possible unless someone adds a complete external data pack system upstream and writes software that builds such packs from a ROM file. Right now compiled executables contain copyrighted resources ripped from the ROM during the build process.

**Comment by ghost** [comment]
Isn't that exactly what [sm64-port/sm64-port](https://github.com/sm64-port/sm64-port) does? It requires you to provide a base ROM for asset extraction.

**Comment by ghost** [comment]
This is what I found in their README file.
> This repo does not include all assets necessary for compiling the game. A prior copy of the game is required to extract the assets.

**Comment by fgsfdsfgs** [comment]
Like I said in my original reply, it's ripped during the build process. Meaning you have to have the ROM available when you're building the executable. Because the data from the ROM is embedded straight into it.

**Comment by ghost** [comment]
Ah, I knew it was ripped during the build process but I wasn't aware that it was embedded into the executable.
