### ISSUE TITLE
No me compila un archivo .pkg en ps3

### ISSUE THREAD

**Issue by hero-hz1999yt** [fgsfdsfgs/sm64-port#41]
utiliza docker para compilar para ps3 pero no me resulta un archivo pkg, solamente archivo .elf, .self

**Comment by fgsfdsfgs** [comment]
In the docker command that you used to build the game, replace `make --jobs` with `make --jobs pkg`. It should make a pkg file next to the .self.

**Comment by Nacheras** [comment]
When you make the pkg, there are two versions, one that says "gnpdrm" and other one without this word. What´s the difference??
Are just the same??

**Comment by fgsfdsfgs** [comment]
I got no idea. Some DRM-related shit probably.

**Comment by Nacheras** [comment]
So it´s better not to use it, though it builds it in your port jejejje
Thanks

**Comment by fgsfdsfgs** [comment]
The packaging tool builds both variants by default. I don't know which one is required since I don't own a PS3.
