### ISSUE TITLE
[xbox] Crashes when wearing both Vanish Cap and Metal Cap

### ISSUE THREAD

**Issue by Nosen92** [fgsfdsfgs/sm64-port#44]
The game crashes when Mario picks up both Vanish cap and Metal Cap.

```
gfx_xbox_wapi_init: resolution 640x480
gfx_xbox_rapi_create_and_load_new_shader: could not find shader for id 09200a00
```

Easiest level to recreate the bug is dire dire docks.

**Comment by fgsfdsfgs** [comment]
I [fixed that](https://github.com/fgsfdsfgs/sm64-port/issues/29) tho. Are you sure you're running the latest commit?

**Comment by Nosen92** [comment]
I might not be.. I'll try to build again and see when I get home if I was running old code. Closing the issue.
