### ISSUE TITLE
Can't build PlayStation 2 port on Windows 7

### ISSUE THREAD

**Issue by 60fpshacksrock** [fgsfdsfgs/sm64-port#46]
Is there any other way than having to use Docker? It doesn't work right on Windows 7, I get some error about VT-X not wanting to work on 7. My PC does have virtualization, and it is enabled in the BIOS. Even VirtualBox works, but not Docker.

**Comment by fgsfdsfgs** [comment]
Yeah, there's instructions right below the Docker instructions. Get a Linux VM in VirtualBox and follow that.

**Comment by 60fpshacksrock** [comment]
After much trial and error, with different Linux versions, (Ubuntu, Debian and Lubuntu) I have finally come really close to making it work (with Linux mint).
However, I am stuck at the CP command. My ROM is located at /home/username/Desktop.
I am not entirely sure what the CP path/to/baserom.us.z64 means. Could you give me an example of how
it should be typed. In the meantime, I'll keep trying.

**Comment by fgsfdsfgs** [comment]
Just put it into the sm64-port folder.

**Comment by 60fpshacksrock** [comment]
I did get it, but there's a new problem.
n64 graphics.c:1:10: fatal error stdio.h No such file or directory

There is more, but copy/paste isn't working from VB to Windows host.

https://ibb.co/t3xTXMD

**Comment by fgsfdsfgs** [comment]
I don't know what the problem is there. (Re)install the `gcc` package maybe?

**Comment by 60fpshacksrock** [comment]
Using Synaptic Package Manager to try and install them separately. 
Hmm...Don't see Python 3 on there, only 2.

**Comment by 60fpshacksrock** [comment]
After installing Python 2.7, and whatever else I could from SPM, I followed your instructions and it worked. 
Thank you.
I was also wondering, have you thought about porting it to PPC? (GC/Wii)

**Comment by fgsfdsfgs** [comment]
I have tried, but I got stuck on some GX graphics memes. Maybe someone else can do it.

**Comment by 60fpshacksrock** [comment]
Oh okay, thanks. Also, I thought this had 60fps. I'm guessing it probably wouldn't work with a ROM patched with Kaze's 60fpsv2 patch.

**Comment by fgsfdsfgs** [comment]
No, you need to apply the 60fps patch before compiling the game. From the current state of your folder probably you need to do something like
```
make clean
git apply enhancements/60fps.patch
```
and then build the game again the same way you built it before.
Do note that while it does unlock the FPS, the game won't reach 60 for the most part. The renderer is too shitty for that.

**Comment by 60fpshacksrock** [comment]
Okay, thanks again. Still might try it sometime.

**Comment by leahanderson1** [comment]
> I have tried, but I got stuck on some GX graphics memes. Maybe someone else can do it.

i am somewhat knowledgeable in GX graphics
if you're still active lmk and i can help you out
