### ISSUE TITLE
Mk64 for Ps2

### ISSUE THREAD

**Issue by JairKuma** [fgsfdsfgs/sm64-port#49]
I would like to ask if you are going to port Mario Kart 64 for ps2, thank you and sorry for create a issue that does not have to do with Super Mario 64

**Comment by fgsfdsfgs** [comment]
The [MK64 decomp](https://github.com/n64decomp/mk64) is not complete enough yet, and after it's complete someone will have to port it to PC first. This has little to do with SM64.
