### ISSUE TITLE
PS2 : compiles without erros with new toolchain but only get a black screen when startup on PS2

### ISSUE THREAD

**Issue by hugorsgarcia** [fgsfdsfgs/sm64-port#53]
![239270425_4521511374549397_1745929227799418058_n](https://user-images.githubusercontent.com/69007691/129761445-88bf8119-4705-4862-9065-a56e5fd43c6e.jpg)
Complies nicely but after you start the game on the PS2 only gives  a black screen

**Comment by fgsfdsfgs** [comment]
Unfortunately I couldn't tell you what the problem is, since I don't have the new toolchain set up right now. Last time I tested was over a year ago with the GCC7-based new toolchain and it worked okay.
What method are you using to load it?

**Comment by hugorsgarcia** [comment]
I got some warnings though

**Comment by hugorsgarcia** [comment]
See if you can replicate this. Use the newest toolchain.

**Comment by skx7** [comment]
I just compiled it via docker on linux and all working fine. I also got the black screen until I pushed a button, I guess I pushed X :) you need to push a button and you will get the Super Mario 64 title screen and all is working super smooth. Great job devs!! Amazing native port 👯

**Comment by hugorsgarcia** [comment]
> n

Wrong. This is not true because is not even possible. The pressing of a button does not interfere on PS2 boot process. There are warnings appearing that do not appear at the old toolchain that is the explanation why is not working. Something in new toolchain was changed and is causing these warnings. I you check then in details later

**Comment by skx7** [comment]
> > n
> 
> Wrong. This is not true because is not even possible. The pressing of a button does not interfere on PS2 boot process. There are warnings appearing that do not appear at the old toolchain that is the explanation why is not working. Something in new toolchain was changed and is causing these warnings. I you check then in details later

I can just confirm I built it with the latest toolchain 3 days ago and it works. Meanwhile I played it more and can confirm the first boot attempt takes more time compared to all others. Maybe it's generating a savegame on the memory card? It works, this I can confirm, maybe pushing the button was pure coincidence on my end. Just sharing my personal feedback 

PS, I built the US version...

**Comment by hugorsgarcia** [comment]
> > > n
> > 
> > 
> > Wrong. This is not true because is not even possible. The pressing of a button does not interfere on PS2 boot process. There are warnings appearing that do not appear at the old toolchain that is the explanation why is not working. Something in new toolchain was changed and is causing these warnings. I you check then in details later
> 
> I can just confirm I built it with the latest toolchain 3 days ago and it works. Meanwhile I played it more and can confirm the first boot attempt takes more time compared to all others. Maybe it's generating a savegame on the memory card? It works, this I can confirm, maybe pushing the button was pure coincidence on my end. Just sharing my personal feedback
> 
> PS, I built the US version...

Wrong again. fjtrujy one of the contributors of ps2sdk just confirmed the problem and did a pull request to fix it. Hence confirming I am right about the issue. Get a look yourself at the pull requests here

**Comment by metchebe** [comment]
Greetings, first of all thank you for the project.

I compiled [32bd7b3](https://github.com/fgsfdsfgs/sm64-port/commit/32bd7b3c77d5a43e347c9ec131d31811a830d32e) this week, following the instructions for building in Docker, and I also have only a black screen when trying to run this on my PS2.

I may have misunderstood but I believe this was fixed, is this indeed the case? Or is there some other fix required to make this work?

I would appreciate any information.

**Comment by xdccrlz** [comment]
Have a black screen too. And size of elf is 14 Mb vs 16 Mb for working elf at 15.10.20 from fgsfdsfgs, compiled on gcc-3.2.3. Help, please. Maybe we need manual fix ps2dev for old toolchain, but code have many fixes, that no working with old toolchain.

**Comment by Brandonmccoub2** [comment]
I have a black screen too, compiled on Ubuntu 20.04 LTS running under WSL1 following the latest guide as of 2022-10-11

**Comment by fgsfdsfgs** [comment]
See #72 for more discussion about this and a temporary solution.
