### ISSUE TITLE
Cannot comment on discord

### ISSUE THREAD

**Issue by 60fpshacksrock** [fgsfdsfgs/sm64-port#64]
I apologize for asking here, but the discord channel won't let me comment. I even clicked on the star emoji.

Anyway, what I wanted to ask you about was if you had any plans of porting Ocarina of Time to consoles.

**Comment by fgsfdsfgs** [comment]
Sorry, I have no idea about the Discord, not an admin/mod there, can't help you with that.
As for OOT, maybe someday.

**Comment by 60fpshacksrock** [comment]
Thank you for the swift reply.
