### ISSUE TITLE
Problems Building the DOS version manually

### ISSUE THREAD

**Issue by godreborn** [fgsfdsfgs/sm64-port#75]
this error occurs with both ubuntu 18.04 and 20.04:

src/pc/pc_main.c: In function 'main_func':
src/pc/pc_main.c:182:6: error: #error Could not pick rendering API!
  182 |     #error Could not pick rendering API!
      |      ^~~~~
compilation terminated due to -Wfatal-errors.
Makefile:887: recipe for target 'build/us_dos/src/pc/pc_main.o' failed
make: *** [build/us_dos/src/pc/pc_main.o] Error 1

**Comment by fgsfdsfgs** [comment]
Did you pass `ENABLE_OPENGL_LEGACY=1` or `ENABLE_SOFTRAST=1` when executing `make`?

**Comment by godreborn** [comment]
thanks, that worked.  I have another issue related to the ps2, but I'll post a new issue on that one.
