### ISSUE TITLE
xbox port, no sound.

### ISSUE THREAD

**Issue by godreborn** [fgsfdsfgs/sm64-port#76]
I can't tell if this is an issue with the emulator or the game, but I get no sound with the xbox port.  I don't have an original xbox to try it on, and it doesn't work on a 360.  the game runs on xemu, just no sound.  I don't know what the problem is.  is this normal, or do you have a suggestion on something to try?  I mean the dos version has sound disabled by default.  thanks.

**Comment by fgsfdsfgs** [comment]
Sound in NXDK homebrew does not work on xemu.
