### ISSUE TITLE
[PS2] Russian translation

### ISSUE THREAD

**Issue by 10522** [fgsfdsfgs/sm64-port#85]
I found a [patch](https://shedevr.org.ru/games/SuperMario64(U)-patch.rar) with Russian translation for USA version. Is it possible to add it to PS2 version?

**Comment by fgsfdsfgs** [comment]
If you patch the baserom with that patch and disable the hash check in the Makefile, it might just work as is. Otherwise no, custom localizations are out of scope for this.

**Comment by Dima353** [comment]
I made Russian translation for several versions
https://github.com/Dima353/SM64-Rus-Patch
