### ISSUE TITLE
[PS2] ELF not recognized

### ISSUE THREAD

**Issue by korbosoft** [fgsfdsfgs/sm64-port#86]
It seems to build without any problems, but when i open it on my PS2, it kicks me back into the menu, and isnt recognized as an ELF file in wLaunchElf.

**Comment by fgsfdsfgs** [comment]
Sounds like you built it for the wrong platform or something. Did you follow the PS2-specific instructions?

**Comment by korbosoft** [comment]
Yes, and it output an ELF file, but the ELF file is not recognized as an actual app.

**Comment by fgsfdsfgs** [comment]
Did you do the [packing step](https://github.com/fgsfdsfgs/sm64-port/tree/ps2#optional-strip-and-pack-resulting-elf)?

**Comment by Korbaux** [comment]
oh, whoops, thought that was optional lole

**Comment by korbosoft** [comment]
No.

**Comment by korbosoft** [comment]
Im using docker, if that helps.

**Comment by metchebe** [comment]
Hi @Korbaux. Just now I made a test build and everything works ok on my slim ps2.

I used the ps2dev docker image as explained [here](https://github.com/fgsfdsfgs/sm64-port/issues/80#issuecomment-1471871695).

**Comment by korbosoft** [comment]
Thanks!
