### ISSUE TITLE
60FPS patch for DOS makes the game hang when loading a level

### ISSUE THREAD

**Issue by stranno** [fgsfdsfgs/sm64-port#9]
Pretty much the same problem as the Playstation 2 version, until your 872b4ce fix.

DOS 60FPS build crashes instantly as soon as you enter Bob-omb Battlefield.

**Comment by fgsfdsfgs** [comment]
Should be fixed in 98be752.

**Comment by stranno** [comment]
Thank you fgsfdsfgs. Closing this issue.
