### ISSUE TITLE
BUG... Cant compile. Error

### ISSUE THREAD

**Issue by wolfmanvid01** [fgsfdsfgs/sm64-port#95]
src/pc/pc_main.c: In function 'init_drivers':
src/pc/pc_main.c:157:9: error: implicit declaration of function 'init_ps2_filesystem_driver' [-Wimplicit-function-declaration]
  157 |         init_ps2_filesystem_driver();
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~
src/pc/pc_main.c: In function 'deinit_drivers':
src/pc/pc_main.c:162:9: error: implicit declaration of function 'deinit_ps2_filesystem_driver' [-Wimplicit-function-declaration]
  162 |         deinit_ps2_filesystem_driver();
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by fgsfdsfgs** [comment]
Either the PS2 SDK has some new breaking changes again or you're using the wrong version. Are you using Docker to build this or are you building manually?

**Comment by wolfmanvid01** [comment]
i tried with docker, with compiling the sdk, and with the binaries of the sdk. And in two different machines. I found out that the SDK got updates 4 days ago

**Comment by wolfmanvid01** [comment]
UPDATE: 

it needed:
   **#include <ps2_filesystem_driver.h>** 
in ./src/pc/pc_main.c. to solve the previous bug

But now i got another error:

src/pc/gfx/gfx_pc.c:391:34: error: passing argument 1 of 'gfx_rapi->upload_texture_ext' from incompatible pointer type [-Wincompatible-pointer-types]
  391 |     gfx_rapi->upload_texture_ext(**_rgba16_buf_**, width, height, G_IM_FMT_RGBA, G_IM_SIZ_16b, NULL);

where "rgba16_buf" got a compilator notification of: 

uint16_t * {aka short unsigned int *}

**Comment by fgsfdsfgs** [comment]
Ah, this is a certified GCC14 moment. For now replace `gfx_rapi->upload_texture_ext(rgba16_buf` with `gfx_rapi->upload_texture_ext((uint8_t *)rgba16_buf`.

**Comment by wolfmanvid01** [comment]
It worked. 

But theres another thing to add before it can compile, and it is
**#include <libmtap.h>**
in src/pc/controller/controller_ps2.c

I tested it and works PERFECT now. Thanks for everything

**Comment by fgsfdsfgs** [comment]
These changes are now in the repo.
